POST http://localhost:8000/order
Content-Type: application/json

{
    "id" : "10",
    "price" : 10500,
    "tax" : 50
}

###

GET http://localhost:8000/order
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8000/