POST http://localhost:8000/order
Content-Type: application/json

{
    "id" : "xxx",
    "price" : 300.33,
    "tax" : 0.5
}

###

GET http://localhost:8000/order
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8000/c